if xuf=="RO" 
    nomeUF="RONDÔNIA"
    cUF="11" 
if xuf=="AC"
    nomeUF="ACRE"
    cUF="12" 
if xuf=="AM" 
    nomeUF="AMAZONAS"
    cUF="13" 
if xuf=="RR" 
    nomeUF="RORAIMA"
    cUF="14" 
if xuf=="PA" 
    nomeUF="PARÁ"
    cUF="15" 
if xuf=="AP" 
    nomeUF="AMAPÁ"
    cUF="16" 
if xuf=="TO" 
    nomeUF="TOCANTINS"
    cUF="17" 
if xuf=="MA" 
    nomeUF="MARANHÃO"
    cUF="21" 
if xuf=="PI" 
    nomeUF="PIAUÍ"
    cUF="22" 
if xuf=="CE" 
    nomeUF="CEARÁ"
    cUF="23" 
if xuf=="RN" 
    nomeUF="RIO GRANDE DO NORTE"
    cUF="24" 
if xuf=="PB" 
    nomeUF="PARAÍBA"
    cUF="25" 
if xuf=="PE" 
    nomeUF="PERNAMBUCO"
    cUF="26" 
if xuf=="AL" 
    nomeUF="ALAGOAS"
    cUF="27" 
if xuf=="SE" 
    nomeUF="SERGIPE"
    cUF="28" 
if xuf=="BA" 
    nomeUF="BAHIA"
    cUF="29" 
if xuf=="MG" 
    nomeUF="MINAS GERAIS"
    cUF="31" 
if xuf=="ES" 
    nomeUF="ESPIRITO SANTO"
    cUF="32" 
if xuf=="RJ" 
    nomeUF="RIO DE JANEIRO"
    cUF="33" 
if xuf=="SP" 
    nomeUF="SÃO PAULO"
    cUF="35" 
if xuf=="PR" 
    nomeUF="PARANÁ"
    cUF="41" 
if xuf=="SC" 
    nomeUF="SANTA CATARINA"
    cUF="42" 
if xuf=="RS" 
    nomeUF="RIO GRANDE DO SUL"
    cUF="43" 
if xuf=="MS" 
    nomeUF="MATO GROSSO DO SUL"
    cUF="50" 
if xuf=="MT" 
    nomeUF="MATO GROSSO"
    cUF="51" 
if xuf=="GO" 
    nomeUF="GOIÁS"
    cUF="52" 
if xuf=="DF" 
    nomeUF="DISTRITO FEDERAL"
    cUF="53" 