def create_updater():
    f = open('Updater.bat', 'w')
    print('@echo off')
    print('@break off')
    print('cls')
    print(' ')
    print('echo Updating...')
    print('echo This process can take up to 2 minutes')
    print('echo .')
    print('echo .')
    print('echo .')
    print(' ')
    print('rmdir bin, config, country, process, select, idocmanager, .git, git /Q/S > NUL')
    print('del __init__.py /Q/F/S > NULdel idocmanager.py /Q/F/S > NUL')
    print('del Iniciar.bat /Q/F/S > NUL')
    print('del README.md /Q/F/S > NUL')
    print('git clone https://github.com/xDhii/idocmanager.git')
    print(' ')
    print('cd idocmanager')
    print('attrib -s -h .git')
    print('echo')
    print('ren .git git')
    print('move git ..')
    print('move bin ..')
    print('move config ..')
    print('move country ..')
    print('move process ..')
    print('move select ..')
    print('move idocmanager.py ..')
    print('move Iniciar.bat ..')
    print('move README.md ..')
    print('move __init__.py')
    print('cd ..')
    print('ren git .git')
    print('attrib +h .git')
    print('rmdir idocmanager /Q/S > NUL')
    print(' ')
    print(' ')
    print('echo Okay, finished ;)')
    print('pause')
    f.close